"""UI protocol shared by ASR controller and Claude driver."""

from __future__ import annotations

from typing import Protocol


# ---------------------------------------------------------------------------
# UI Protocol
# ---------------------------------------------------------------------------

class _UI(Protocol):
    def set_status(self, status: str) -> None: ...
    def set_partial(self, text: str) -> None: ...
    def add_user_message(self, text: str) -> None: ...
    def add_assistant_text(self, text: str) -> None: ...
    def add_tool_use(self, label: str) -> None: ...
    def add_error_message(self, text: str) -> None: ...
    def speak(self, text: str) -> None: ...
    async def speak_and_wait(self, text: str) -> None: ...
    def finalise_assistant_turn(self) -> None: ...
